### ISSUE TITLE
algoliaanalytics-node is not found in the npm registry -- Error 

### ISSUE THREAD

**Issue by JohnwesleyD** [acemtp/meteor-algolia#2]
I am trying to use the algolia seach capability in my meteor app and was able to add the meteor-search package from atmosphere (acemtp:algolia). All is well when i run the project locally.

The issue occurs when i try to deploy the app on Modulus. It has a dependency on the algoliaanalytics-node and wants the author to publish to npm registry.

Do you have any work around as in can i install the algolia-search locally and deploy them without the algoliaanalytics-node dependency...

Any help with this is greatly appreciated. :)

**Comment by acemtp** [comment]
I don't understand why I didn't see your issue notification.

I just updated to latest algolia version.
