### ISSUE TITLE
Upgrade to isomorphic algoliasearch V3

### ISSUE THREAD

**Issue by redox** [acemtp/meteor-algolia#5]
Maybe @vvo could help?

**Comment by acemtp** [comment]
I'll take a look at this tomorrow. I want to update fastosphere project so it's a good thing to do.

**Comment by redox** [comment]
:+1:

**Comment by vvo** [comment]
Great, let me know if you need any help @acemtp

**Comment by acemtp** [comment]
I moved to algolia 3.3.2, updated the example and now client and server use the global AlgoliaSearch object like all other meteor packages.

**Comment by vvo** [comment]
great!
