### ISSUE TITLE
Include algoliasearch.js from a submodule

### ISSUE THREAD

**Issue by dandv** [acemtp/meteor-algolia#6]
Would cleanly isolate this wrapper from the upstream, and would make updating easier (the current version is now 3.3.2)

Right now we have a [competing package that has only updated the .js file](https://github.com/yubozhao/meteor-algolia/commits/master) to 2.9.2 and republished. With http://autopublish.meteor.com, this wrapper could always be kept in sync with the latest version of Algolia.

BTW @vvo, what repo has the latest algoliasearch.js? PS: [the FAQ uses an older version, 2.9.0](https://github.com/algolia/AlgoliaFAQ/blob/master/_assets/vendors/algoliasearch.js), and the copyright year there is 2013.

**Comment by vvo** [comment]
So the latest algoliasearch build can always be found:
- on github: https://github.com/algolia/algoliasearch-client-js/tree/master/dist, algoliasearch.min.js or algoliasearch.js
- on jsdelivr: http://cdn.jsdelivr.net/algoliasearch/3/algoliasearch.min.js or http://cdn.jsdelivr.net/algoliasearch/3/algoliasearch.js

**Comment by dandv** [comment]
Thanks @vvo. The un-minified file is best, since Meteor automatically concatenates and minifies.

@acemtp, here's an example of wrapping a 3rd party library in a submodule: https://github.com/MeteorPackaging/webix-skin-touch

**Comment by acemtp** [comment]
I added a submodule
