### ISSUE TITLE
Tons of duplicate console logs

### ISSUE THREAD

**Issue by webyak** [acemtp/meteor-algolia#7]
W20150528-17:50:52.408(2)? (STDERR) Thu, 28 May 2015 15:50:52 GMT algoliasearch:/1/indexes/****/**** sent/remaining bytes: 1087/490

Just curious if you also get a ton of logs like these when saving or updating an Algolia record? Everything else works fine so far.

Edit: Looks like this got fixed @3.4.0 (https://github.com/algolia/algoliasearch-client-js/blob/master/ChangeLog#L10)

**Comment by acemtp** [comment]
Thanks for the feedback.

This logs are from algolia lib.

I moved to the latest algolia version 3.4.0 and they are gone.

So you just have to `meteor update`
